extends:
  - airbnb/base
  - airbnb-typescript/base



rules:
  semi: [error, never]
  no-constant-binary-expression: error
  '@typescript-eslint/no-inferrable-types': error
  '@typescript-eslint/semi': [error, never]
  '@typescript-eslint/member-delimiter-style': [error, {
    multiline: { delimiter: none },
    singleline: { delimiter: comma }
  }]
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': error
  '@typescript-eslint/prefer-ts-expect-error': error
  '@typescript-eslint/type-annotation-spacing': error
  '@typescript-eslint/naming-convention': off
  arrow-parens: [error, as-needed]
  no-param-reassign: warn
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-implied-eval': off
  import/no-webpack-loader-syntax: off
  import/prefer-default-export: off
  camelcase: off
  consistent-return: off
  implicit-arrow-linebreak: off
  max-classes-per-file: off
  max-len: off
  newline-per-chained-call: off
  no-alert: off
  no-await-in-loop: off
  no-bitwise: off
  no-console: off
  no-continue: off
  no-nested-ternary: off
  no-new: off
  no-plusplus: off
  no-restricted-syntax: off
  no-underscore-dangle: off
  object-curly-newline: off
  prefer-template: off
